### ISSUE TITLE
TextBounds replacement with GlyphLayout

### ISSUE THREAD

**Issue by pantinor** [kotcrab/JDialogue#2]
public class KotcrabText {
  private GlyphLayout textBounds;

**Comment by kotcrab** [comment]
It uses libgdx version in which `GlyphLayout` haven't existed yet. `KotcrabText` is very old class and it needs full rewrite anyways. This project is abandoned.

**Comment by pantinor** [comment]
Yeah I saw that.  Just noticed these things.  Cool idea I liked it.  I was
looking for something like scxml but more focused on conversations for rpg.

**Comment by kotcrab** [comment]
Yeah it was pretty neat idea, maybe I will come back to this project at some point but if that ever happens I would rewrite it from scratch anyways. I wrote it when I didn't know that much about programming so code quality is rather low. Also It mixes Swing and libGDX for GUI and Swing is pain to use.
